[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AutoDeploy"
description = "Auto deployment for ArkViewer and ArkHandler"
readme = "README.md"
